name: Deploy code.gouv.fr website to production

on:
  push:
    branches: ["production"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Build with Eleventy
        run: |
          npm install
          npm run build-production
      - name: Index site for pagefind
        run: npm run postbuild
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # must be in PEM format
          ARGS: "-av --delete"
          SOURCE: _site/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST_PROD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER_PROD }}
          TARGET: ${{ secrets.REMOTE_TARGET_PROD }}
